# Generated by Django 4.1.1 on 2022-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=60)),
                ('landmark', models.TextField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('shopCategory', models.CharField(max_length=20)),
                ('shopImage', models.ImageField(upload_to='media')),
            ],
        ),
    ]
