# Generated by Django 4.1.1 on 2022-10-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='landmark',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopName',
            field=models.CharField(max_length=20),
        ),
    ]
